name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2

    - run: npm ci
    - run: npm run lint

  test:
    needs: lint

    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        node:
        - 10

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}

    # simulate a system that doesn't generate valid diffs
    # https://github.com/ember-cli/ember-cli-update/issues/995
    - run: git config --global diff.noprefix true

    - run: npm ci
    - run: npm test
      env:
        DEBUG: git-diff-apply,git-fixtures

  ember-cli-update:
    needs: test
    if: github.event_name == 'pull_request'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.GitHubToken }}
    - uses: actions/setup-node@v2
    - uses: kellyselden/ember-cli-update-action@v2
      with:
        autofix_command: npm run lint -- --fix
        ignore_to: true
